name: Build
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - ".github/**"
      - "SOGFramework/core/main/script_version.hpp"
      - "tools/**"
      - ".gitignore"

jobs:
  build-framework:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{  steps.bump-version.outputs.VERSION }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master
        with:
          ref: master
          
      - name: Bump version
        id: bump-version
        run: python3 tools/version_bumper.py increment_build push_commit
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SOGFramework_v${{ steps.bump-version.outputs.VERSION }}
          path: |
            SOGFramework/
            cba_settings.sqf
            description.ext
            README.md

  release-framework:
    runs-on: ubuntu-latest
    needs: build-framework
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: SOGFramework_v${{ needs.build-framework.outputs.output1 }}

      - name: Archive Framework Content
        uses: thedoctor0/zip-release@master
        with:
          filename: SOGFramework_v${{ needs.build-framework.outputs.output1 }}.zip
          path: |
            SOGFramework/
            cba_settings.sqf
            description.ext
            README.md

      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build-framework.outputs.output1 }}
          release_name: SOGFramework_v${{ needs.build-framework.outputs.output1 }}
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./SOGFramework_v${{ needs.build-framework.outputs.output1 }}.zip
          asset_name: SOGFramework_v${{ needs.build-framework.outputs.output1 }}.zip
          asset_content_type: application/zip